server:
  port: 8888

spring:
    datasource:
      url: jdbc:mysql://localhost:3306/dl_db?characterEncoding=utf-8
      username: root
      password: 123456
      sql-script-encoding: utf-8
      driver-class-name: com.mysql.jdbc.Driver
      type: com.alibaba.druid.pool.DruidDataSource
      initial-size: 5
      min-idle: 5
      max-active: 200
      max-wait: 60000
      time-between-eviction-runs-millis: 60000
      min-evictable-idle-time-millis: 300000
      validation-query: SELECT 1 FROM DUAL
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      filters:
#      maxPoolPreparedStatementPerConnectionSize: 20
      connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
      useGlobalDataSourceStat: true
      removeAbandoned:  true
      removeAbandonedTimeout: 20
      logAbandoned: false
    redis:
      host: localhost
      password: pass123
      port: 6379
      database: 0
      timeToLive: 1

flyway:
    setBaselineOnMigrate: true




