spring:
  application:
    name: @project.artifactId@
  profiles:
    active: local
server:
  port: 8888
  ssl:
    clientAuth: want
    protocol: TLS
    enabled: false
logging:
  level:
    root: INFO
    com.zhongan: DEBUG
    org.mybatis: INFO
    org.apache.http: INFO


