CREATE TABLE t_user(
  user_id INT NOT NULL PRIMARY KEY AUTO_INCREMENT COMMENT '用户id' ,
  user_name VARCHAR(255) NOT NULL COMMENT '用户名' ,
  password VARCHAR(255) NOT NULL COMMENT '密码' ,
  phone_num VARCHAR(255) NOT NULL COMMENT'电话'
) ENGINE=INNODB DEFAULT CHARSET=utf8 COMMENT '用户表';